site_name: Git  Notes
site_description: My organized notes for Git
theme:
  name: material
  palette:
    primary: brown
    accent: grey
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Git Basics:
      - Introduction: Introduction.md
      - DiveDeeper: DiveDeeperIntoBasics.md
      - Git Essentials- reset, revert: gitEssentials.md
  - Branches:
      - Intro to Branching: branching.md
      - Branches In Depth: branchDiagram.md
  - Merging:
      - Intro to Merging: merging.md
      - Resolving Merge conflicts: mergeConflicts.md
  - Cherry Pick: git_cherrypick.md
  - Remote Repo: remotes.md
  - GitLab: gitLab.md
  - Rebasing: rebasing.md
